# https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/common/callbacks/ema.py

exponetial_moving_average:
  _target_: src.callbacks.ema.EMA
  decay: 0.9999
  validate_original_weights: False
  every_n_steps: 1
  cpu_offload: False
