_target_: src.models.vae_module.VariationalAutoencoderLitModule

encoder: ${encoder}
decoder: ${decoder}

latent_dim: 8

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler: null

scheduler_frequency: ${trainer.check_val_every_n_epoch}

# TODO rename mp20 -> periodic, qm9 -> non-periodic
loss_weights:
  loss_atom_types:
    mp20: 1.0
    qm9: 1.0
  loss_lengths:
    mp20: 1.0
    qm9: 0.0
  loss_angles:
    mp20: 10.0
    qm9: 0.0
  loss_frac_coords:
    mp20: 10.0
    qm9: 0.0
  loss_pos:
    mp20: 0.0
    qm9: 10.0
  loss_kl:
    mp20: 0.00001
    qm9: 0.00001

augmentations:
  noise: 0.1  # proportion of atoms to perturb
  frac_coords: true
  pos: true

visualization:
  visualize: true
  save_dir: ${paths.viz_dir}/

# compile model for faster training with pytorch 2.0
compile: false
