program: src/eval_diffusion.py

method: grid

metric: # Does not matter, as we are using sweep to run the experiment.
  goal: minimize
  name: test/loss

parameters:
  data:
    value: joint

  diffusion_module:
    value: ldm

  seed:
    value: 9

  ckpt_path:
    value: ...
  # Or set manually in configs/diffusion_module/ldm.yaml

  ++diffusion_module.autoencoder_ckpt:
    value: ...
  # # Or set manually in configs/eval_diffusion.yaml

  ++diffusion_module.interpolant.num_timesteps:
    values: [
      25,
      50,
      100,
      250,
      500,
      1000,
    ]

  ++diffusion_module.sampling.cfg_scale:
    values: [
      1.0,
      2.0,
      3.0,
      4.0,
      6.0,
      8.0,
    ]

  ++diffusion_module.sampling.num_samples:
    value: 10000

  ++diffusion_module.sampling.batch_size:
    value: 1000

  trainer:
    value: gpu

  logger:
    value: wandb

  name:
    value: "eval_nt@${diffusion_module.interpolant.num_timesteps}_cfg@${diffusion_module.sampling.cfg_scale}"

command:
  - ${env}
  - HYDRA_FULL_ERROR=1
  - WANDB_START_METHOD=thread
  - python
  - ${program}
  - ${args_no_hyphens}
