_target_: src.models.encoders.equiformer.EquiformerEncoder

use_pbc: False  # set to false for non-periodic systems (e.g. molecules)
otf_graph: True
max_neighbors: 20
max_radius: 9.0
max_num_elements: 100

num_layers: 8
sphere_channels: 128
attn_hidden_channels: 64
num_heads: 8
attn_alpha_channels: 64
attn_value_channels: 16
ffn_hidden_channels: 128

norm_type: layer_norm_sh

lmax_list: [2]
mmax_list: [1]
grid_resolution: 18

num_sphere_samples: 128

edge_channels: 128
use_atom_edge_embedding: true
share_atom_edge_embedding: false
use_m_share_rad: false
distance_function: gaussian
num_distance_basis: 512

attn_activation: silu
use_s2_act_attn: false
use_attn_renorm: true
ffn_activation: silu
use_gate_act: false
use_grid_mlp: true
use_sep_s2_act: true

alpha_drop: 0.1
drop_path_rate: 0.1
proj_drop: 0.0

weight_init: uniform
